import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import rexItems from "./docs/rex/api/sidebar";

const sidebars: SidebarsConfig = {
    about: [
        {
            type: "autogenerated",
            dirName: "about",
        },
    ],
    // TODO: add back when we have minutes pages
    minutes: [
        {
            type: "category",
            label: "Minutes",
            link: {
                type: "generated-index",
                title: "DormCon Meeting Minutes",
                description:
                    "Meeting minutes for all of our meetings, organized by semester. Click below to view the minutes for each semester!",
                slug: "/minutes",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "minutes",
                },
                {
                    type: "link",
                    label: "Archived Minutes on Old Site",
                    href: "https://web.mit.edu/dormcon/minutes/",
                },
            ],
        },
    ],
    rex: [
        {
            type: "category",
            label: "REX API",
            link: {
                type: "generated-index",
                title: "REX API",
                description:
                    "Automatically generated documentation for the REX API. Click below to see various aspects of the API.",
                slug: "/rex/api",
            },
            items: rexItems as SidebarsConfig[string],
        },
    ],
};

export default sidebars;
